apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitright-frontend
  labels:
    app: splitright
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splitright
      tier: frontend
  template:
    metadata:
      labels:
        app: splitright
        tier: frontend
    spec:
      containers:
        - name: splitright-frontend
          image: 324037286174.dkr.ecr.ap-southeast-2.amazonaws.com/splitright-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://splitright-backend.default.svc.cluster.local"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: splitright-frontend
  labels:
    app: splitright
    tier: frontend
spec:
  selector:
    app: splitright
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
